name: Backend CI (Java/Maven)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api-gateway/**'
      - 'eureka-service/**'
      - 'notification-service/**'
      - 'order-service/**'
      - 'restaurant-service/**'
      - 'user-service/**'
      - 'pom.xml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'api-gateway/**'
      - 'eureka-service/**'
      - 'notification-service/**'
      - 'order-service/**'
      - 'restaurant-service/**'
      - 'user-service/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - 'api-gateway'
          - 'eureka-service'
          - 'notification-service'
          - 'order-service'
          - 'restaurant-service'
          - 'user-service'

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build ${{ matrix.service }}
      run: mvn -B clean install --file ${{ matrix.service }}/pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
